AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example of processing messages to SQS queue with Lambda
Resources:
  MySQSQueueFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "Karmel"
      Handler: index.lambda_handler
      Runtime: python3.8
      Policies:
      # Give the Lambda service access to SQS
      - AmazonSQSFullAccess